### ISSUE TITLE
Power Spectral Density

### ISSUE THREAD

**Issue by nickbsb** [royalosyin/Python-Practical-Application-on-Climate-Variability-Studies#3]
Hi, I am a beginner in learning Python. In 'Power Spectral Density’.In my opinion,for monthly data, the results are divided by 12 to calculate annual cycles like this  'plt.plot(1.0/f1[1:47]/12, pxx1[1:47], label='welch')',but for annual data,how to deal with it？I tried not to divide by 12，but   
the maximum period of abscissa is 250 years，this may be something wrong .Could you help me to solve this problem? Look forward for your reply.

**Comment by royalosyin** [comment]
In fact, you can plot the result of the Welch method directly. Thus, you can find the maximum  PSD and its frequency. Then convert the frequency to years.
plt.semilogy(f1, pxx1)
plt.ylim([0.5e-3, 1])
plt.xlabel('frequency [Hz]')
plt.ylabel('PSD [V**2/Hz]')
plt.show()

They follow some relationships. Let fs be the sampling rate, thus, the sampling time is dt = 1/fs. If the sampling point is N, then the total duration is T = N* dt and the interval of the spectral points is df = 1/T.

**Comment by nickbsb** [comment]
Got it，thank you very much.In order to show the credibility of the signal,confidence test is often needed for power spectral density signals like  statistical significance at a confidence level better than 95%. How to do this?

**Comment by royalosyin** [comment]
https://www.researchgate.net/post/How_to_calculate_the_confidence_interval_of_a_given_PSD_with_Python2
