### ISSUE TITLE
Continuous Wavelet Spectrum - Example for NINO3 SST 

### ISSUE THREAD

**Issue by nickbsb** [royalosyin/Python-Practical-Application-on-Climate-Variability-Studies#4]
In'Continuous Wavelet Spectrum - Example for NINO3 SST ',Here lag1 = 0.72,both α1 and α2 >0. TC98 says explicitly that "this red-noise was estimated from( α1+√α2) /2 where α1and α2 are the lag-1 and lag-2 autocorrelations of the Niño3 SST". So this is NOT a constant value, valid for each and every time series, but one which must be estimated. 
when α1<0,especially α2<0,how to compute it? Look forward for your reply.

**Comment by royalosyin** [comment]
In practice, the function only requires lag1 when you calculate sig. And you can calculate it directly from the original time series. In the tutorial set lag1=0.72 only for reproducing the paper. In addition, you also can refer to the example in NCL language, which is a complete case. The NCL version calculates lag1 inside the main function.
