### ISSUE TITLE
Error in lmoments.quanor

### ISSUE THREAD

**Issue by Jahangirali09** [royalosyin/Python-Practical-Application-on-Climate-Variability-Studies#5]
Hi, I am working with the SPI code. The code is running fine until it computes the dim_spi_n. I am getting the following error
![lmoments quanor](https://user-images.githubusercontent.com/60271133/107134058-3656eb00-68b4-11eb-93a7-8d0828a95624.png)

When it read the probability values in lmoments.quannor and goes to the function quanor(F,para), here it is getting the F values which are not iterable. Any suggestions why is it happening. I am working with the sample netcdf file as used in your code.

**Comment by royalosyin** [comment]
First, check your data.  It seems that the lmoments is not compatible with the latest version of scipy. So you can also test the fuction of quanor with artificial data to check if the problem comes with lmoments.

**Comment by Jahangirali09** [comment]
Thank you for response. The parameters in line 27 above are invalid. Here, we are giving the parameters to lmoments.quanor(probability, (0.0,1.0)) and in the quanor function quanor(F, para), we have defined values less than or equal to zero as invalid. Shouldn't the function quanor(F,para) take the parameter values from gamma distribution?
![quano](https://user-images.githubusercontent.com/60271133/107279259-6caf7a00-6a1c-11eb-82dd-082d37e89cc2.png)

**Comment by royalosyin** [comment]
In  quanor(F,para),  para=(0.0, 1.0) is used to limit the probability from a normal dist to 0-1. The problem may come from the calculation of F.  You can find the grid with an error to extract the data at the grid. Then manually check the issue step by step.

**Comment by Jahangirali09** [comment]
Is there any underlying assumption with the input data? I am using the same file V22_GPCP.1979-2010.nc as used in the code.
The probability calculated from dim_spi_n function is non iterable, it means it is returning a constant value. Should I expect to get a range of probability values:
![dimspi](https://user-images.githubusercontent.com/60271133/107299040-33870200-6a3c-11eb-8958-f4dd8f238b00.png)

In dim_spi_n function, line 22 the initial probability value is set 0.0 and then at line 29 it is again calculated from lmoments.cdfgam. Is it necessary to set the first probability value=0.0?

**Comment by royalosyin** [comment]
In fact, you can use try...catch. Once an error occurs, just skip that grid. In addition, the return value from the line 29 will overwrite the probabilities=0.0 in the line 22. It is a good practice to assign an initial value to a variable before using it.
The basic assumption  is that the precipitation could be fitted into a Gamma distribution. Maybe it is not true for some places. So some SPI calculations may use a pearson dist.

**Comment by Jahangirali09** [comment]
Can you post here here how to use try....catch? And also in general what should be the probability values. It must be a list I believe to satisfy F in lmoment.quanor. Is that correct?

**Comment by Jahangirali09** [comment]
I have checked it with separate grid values and the issue is not with the input data. I have even checked with random input data and ran the dim_spi_n function, the code is unable to compute the probability.

**Comment by royalosyin** [comment]
The tutorial is written in python2. Maybe, you can try lmoments3. However, scipy updated very frequently, the lmoments3 also may not work. In fact, you just need to know the idea behind SPI, mapping the probability from a gamma distribution to a normal distribution.

**Comment by Jahangirali09** [comment]
I am interested in spatial representation of SPI. This code looks interesting to me and I would like to push it further to see if I can make any changes and be able to run it. Can your share your e-mail, I couldn't find your email on github. My email is jahangirclimate9@gmail.com.
